namespace com.sap.bdc;

using { cuid, managed, temporal } from '@sap/cds/common';

entity ARMaster : cuid, managed {
  RequestID__c : String(50);
  Submitter__c : String(100);
  CreateDate__c : Date;
  AssignedTo__c : String(100);
  LastModifiedBy__c : String(100);
  ModifiedDate__c : Date;
  Status__c : String(20);
  APPROVAL_STATUS : String(20) default 'Sent for Approval';
  ShortDescription__c : String(255);
  NotifierListening : String(100);
  AccessCode : String(50);
  RecordID : String(50);
  ValidFrom : Date;
  RoleStatus : String(20);
  AdditionalData__c : String(1000);
  ServiceName : String(100);
  RoleName : String(50);
  EntityName : String(50);
  TrigramCompany : String(10);
  CountryLocation : String(50);
  CompanyCode : String(10);
  ValidTo : Date;
  PurchaseOrganization : String(50);
  SalesOrganization : String(50);
  OrganizationUnit : String(50);
  RegionSite : String(50);
  Reminder1Sent : Boolean;
  MarketArea : String(50);
  ARSignum : String(50);
  BusinessUnit : String(50);
  BAOFrom : String(50);
  BAOTo : String(50);
}

entity ARChangeLog : cuid {
  REQUEST_ID__C : String(50);
  MODIFIED_DATE__C : Date;
  LAST_MODIFIED_BY__C : String(100);
  CREATE_DATE__C : Date;
  SUBMITTER__C : String(100);
  ORDER_ID : String(50);
  DATEORDERED : Date;
  ASSIGNED_TO__C : String(100);
  STATUS__C : String(20);
  APPROVAL_STATUS : String(20) default 'Sent for Approval';
  SHORT_DESCRIPTION__C : String(255);
  HANDLER : String(100);
  REQUESTOR : String(100);
  REQUESTTYPE : String(50);
  SERVICE_NAME : String(100);
  ROLE_NAME : String(50);
  ENTITY_NAME : String(50);
  TRIGRAM_COMPANY : String(10);
  COUNTRY_LOCATION : String(50);
  COMPANY_CODE : String(10);
  BUSINESS_UNIT : String(50);
  PURCHASE_ORGANIZATION : String(50);
  SALES_ORGANIZATION : String(50);
  ORGANIZATION_UNIT : String(50);
  REGION_SITE : String(50);
  AR_SIGNUM : String(50);
  VALID_FROM : Date;
  VALID_TO : Date;
  MARKET_AREA : String(50);
  APPROVER : String(100);
  ADDITIONAL_INFO : String(1000);
  ACCESS_TYPE : String(50);
  ACCESS_KEY : String(50);
  ADDITIONAL_DATA__C : String(1000);
  REQUEST_ID : String(50);
  BAO_FROM : String(50);
  BAO_TO : String(50);
  STATUS_HISTORY : String(1000);
  REFRESH_DATE : Date;
}

entity ApproverMaster : cuid {
  RequestID : String(50);
  AssignedTo__c : String(100);
  CreateDate : Date;
  Submitter__c : String(100);
  LastModifiedBy : String(100);
  ModifiedDate : Date;
  Status__c : String(20);
  ShortDescription : String(255);
  StatusHistory : String(1000);
  RefValue1 : String(100);
  DataType : String(50);
  ServiceName : String(100);
  RefValue5 : String(100);
  RefValue4 : String(100);
  RefValue3 : String(100);
  RefValue2 : String(100);
  Approvers : String(500);
  FulfillmentTeams : String(500);
  Company : String(100);
  DocumentName : String(255);
  SAPLocation : String(100);
  ResourceName : String(100);
  SourceResourceID : String(50);
  ApproverName : String(100);
  SourceSystem : String(100);
  RefValue6 : String(100);
  RefValue7 : String(100);
  RefValue8 : String(100);
  RefValue9 : String(100);
}

entity ApproverChangeLog : cuid {
  REQUEST_ID__C : String(50);
  MODIFIED_DATE__C : Date;
  LAST_MODIFIED_BY__C : String(100);
  CREATE_DATE__C : Date;
  SUBMITTER__C : String(100);
  ORDER_ID : String(50);
  DATEORDERED : Date;
  ASSIGNED_TO__C : String(100);
  STATUS__C : String(20);
  SHORT_DESCRIPTION__C : String(255);
  HANDLER : String(100);
  REQUESTOR : String(100);
  REQUESTTYPE : String(50);
  SERVICE_NAME : String(100);
  ROLE_NAME : String(50);
  ENTITY_NAME : String(50);
  TRIGRAM_COMPANY : String(10);
  COUNTRY_LOCATION : String(50);
  COMPANY_CODE : String(10);
  BUSINESS_UNIT : String(50);
  PURCHASE_ORGANIZATION : String(50);
  SALES_ORGANIZATION : String(50);
  ORGANIZATION_UNIT : String(50);
  REGION_SITE : String(50);
  AR_SIGNUM : String(50);
  VALID_FROM : Date;
  VALID_TO : Date;
  MARKET_AREA : String(50);
  APPROVER : String(100);
  ADDITIONAL_INFO : String(1000);
  ACCESS_TYPE : String(50);
  ACCESS_KEY : String(50);
  ADDITIONAL_DATA__C : String(1000);
  REQUEST_ID : String(50);
  BAO_FROM : String(50);
  BAO_TO : String(50);
  STATUS_HISTORY : String(1000);
  REFRESH_DATE : Date;
}